import { ChainId } from "./networks"
import type { IconFetchItem, IconAlias } from "./icons"
import { IconKind } from "./icons"

/** Chain icon fetch list. Generated from scripts/_fetch-chain-icons.ts. */
export const chainIconFetchItems = [
	/** Unichain: unichain.org/assets/zip/unichain-brand-kit.zip (official brand kit; icon, lockup, vertical lockup) */
	{ target: 'chain' as const,
		id: ChainId.Unichain,
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.unichain.org/assets/zip/unichain-brand-kit.zip',
			pathInZip:
				'Unichain Brand Kit /Unichain Logo Assets/Network icons/Mainnet.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Unichain,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.unichain.org/assets/zip/unichain-brand-kit.zip',
			pathInZip:
				'Unichain Brand Kit /Unichain Logo Assets/Unichain Icon - Dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Unichain,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.unichain.org/assets/zip/unichain-brand-kit.zip',
			pathInZip:
				'Unichain Brand Kit /Unichain Logo Assets/Unichain Icon - Light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Unichain,
		kind: IconKind.Logo,
		style: 'vibrant',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.unichain.org/assets/zip/unichain-brand-kit.zip',
			pathInZip:
				'Unichain Brand Kit /Unichain Logo Assets/Unichain Icon - Vibrant.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Unichain,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.unichain.org/assets/zip/unichain-brand-kit.zip',
			pathInZip:
				'Unichain Brand Kit /Unichain Logo Assets/Unichain Lockup - Dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Unichain,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.unichain.org/assets/zip/unichain-brand-kit.zip',
			pathInZip:
				'Unichain Brand Kit /Unichain Logo Assets/Unichain Lockup - Light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Unichain,
		kind: IconKind.LogoAndWordmark,
		style: 'vibrant',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.unichain.org/assets/zip/unichain-brand-kit.zip',
			pathInZip:
				'Unichain Brand Kit /Unichain Logo Assets/Unichain Lockup - Vibrant.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Unichain,
		kind: IconKind.LogoAndWordmark,
		style: 'vertical-light',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.unichain.org/assets/zip/unichain-brand-kit.zip',
			pathInZip:
				'Unichain Brand Kit /Unichain Logo Assets/Unichain Vertical  Lockup - Light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Unichain,
		kind: IconKind.LogoAndWordmark,
		style: 'vertical-dark',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.unichain.org/assets/zip/unichain-brand-kit.zip',
			pathInZip:
				'Unichain Brand Kit /Unichain Logo Assets/Unichain Vertical Lockup - Dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Unichain,
		kind: IconKind.LogoAndWordmark,
		style: 'vertical-vibrant',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.unichain.org/assets/zip/unichain-brand-kit.zip',
			pathInZip:
				'Unichain Brand Kit /Unichain Logo Assets/Unichain Vertical Lockup - Vibrant.svg',
		},
	},
	/** Plume: docs.plumenetwork.xyz/plume/community-and-support/brand-assets (GitBook SVG zip) */
	{ target: 'chain' as const,
		id: ChainId.Plume,
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://4283780171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FcaO8bqNQ5CJfDyLKmEZF%2Fuploads%2FhACgnZH9YAp6HsArymxz%2FPlume%20Media%20Kit%20-%20SVG.zip?alt=media&token=801bc6e8-cf27-4c9b-8141-935a6e2b663f',
			pathInZip: 'Logomark Red.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Plume,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://4283780171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FcaO8bqNQ5CJfDyLKmEZF%2Fuploads%2FhACgnZH9YAp6HsArymxz%2FPlume%20Media%20Kit%20-%20SVG.zip?alt=media&token=801bc6e8-cf27-4c9b-8141-935a6e2b663f',
			pathInZip: 'Logomark Dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Plume,
		kind: IconKind.Logo,
		style: 'white',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://4283780171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FcaO8bqNQ5CJfDyLKmEZF%2Fuploads%2FhACgnZH9YAp6HsArymxz%2FPlume%20Media%20Kit%20-%20SVG.zip?alt=media&token=801bc6e8-cf27-4c9b-8141-935a6e2b663f',
			pathInZip: 'Logomark White.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Plume,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://4283780171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FcaO8bqNQ5CJfDyLKmEZF%2Fuploads%2FhACgnZH9YAp6HsArymxz%2FPlume%20Media%20Kit%20-%20SVG.zip?alt=media&token=801bc6e8-cf27-4c9b-8141-935a6e2b663f',
			pathInZip: 'Full Logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Plume,
		kind: IconKind.LogoAndWordmark,
		style: 'black',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://4283780171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FcaO8bqNQ5CJfDyLKmEZF%2Fuploads%2FhACgnZH9YAp6HsArymxz%2FPlume%20Media%20Kit%20-%20SVG.zip?alt=media&token=801bc6e8-cf27-4c9b-8141-935a6e2b663f',
			pathInZip: 'Full Logo Black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Plume,
		kind: IconKind.LogoAndWordmark,
		style: 'white',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://4283780171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FcaO8bqNQ5CJfDyLKmEZF%2Fuploads%2FhACgnZH9YAp6HsArymxz%2FPlume%20Media%20Kit%20-%20SVG.zip?alt=media&token=801bc6e8-cf27-4c9b-8141-935a6e2b663f',
			pathInZip: 'Full Logo White.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Plume,
		kind: IconKind.Logo,
		style: 'red-bg',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://4283780171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FcaO8bqNQ5CJfDyLKmEZF%2Fuploads%2FhACgnZH9YAp6HsArymxz%2FPlume%20Media%20Kit%20-%20SVG.zip?alt=media&token=801bc6e8-cf27-4c9b-8141-935a6e2b663f',
			pathInZip: 'Logomark-BG-Red.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Plume,
		kind: IconKind.Logo,
		style: 'black-bg',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://4283780171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FcaO8bqNQ5CJfDyLKmEZF%2Fuploads%2FhACgnZH9YAp6HsArymxz%2FPlume%20Media%20Kit%20-%20SVG.zip?alt=media&token=801bc6e8-cf27-4c9b-8141-935a6e2b663f',
			pathInZip: 'Logomark-BG-Black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Plume,
		kind: IconKind.LogoAndWordmark,
		style: 'powered-by',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://4283780171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FcaO8bqNQ5CJfDyLKmEZF%2Fuploads%2FhACgnZH9YAp6HsArymxz%2FPlume%20Media%20Kit%20-%20SVG.zip?alt=media&token=801bc6e8-cf27-4c9b-8141-935a6e2b663f',
			pathInZip: 'Powered by Plume.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Plume,
		kind: IconKind.LogoAndWordmark,
		style: 'inverted',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://4283780171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FcaO8bqNQ5CJfDyLKmEZF%2Fuploads%2FhACgnZH9YAp6HsArymxz%2FPlume%20Media%20Kit%20-%20SVG.zip?alt=media&token=801bc6e8-cf27-4c9b-8141-935a6e2b663f',
			pathInZip: 'Powered by Plume Inverted.svg',
		},
	},
	/** Ink: docs.inkonchain.com (official brand kit; PNG only — symbol + full logo + safe-margin variants) */
	{ target: 'chain' as const,
		id: ChainId.Ink,
		fetch: {
			fetchType: 'png',
			url: 'https://docs.inkonchain.com/images/brand-kit/docs-logo-symbol.png',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ink,
		kind: IconKind.Logo,
		style: 'safe-margin',
		fetch: {
			fetchType: 'png',
			url: 'https://docs.inkonchain.com/images/brand-kit/docs-logo-symbol-margin.png',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ink,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'png',
			url: 'https://docs.inkonchain.com/images/brand-kit/docs-logo-wordmark.png',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ink,
		kind: IconKind.LogoAndWordmark,
		style: 'safe-margin',
		fetch: {
			fetchType: 'png',
			url: 'https://docs.inkonchain.com/images/brand-kit/docs-logo-wordmark-margin.png',
		},
	},
	/** Ethereum: ethereum.org/assets (Brand assets); chain logo/light from etherscan.io (explorer) */
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-glyph.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://etherscan.io/images/svg/brands/ethereum-original.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://etherscan.io/images/svg/brands/ethereum-original-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'black',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'purple',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-purple.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'white',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-purple-white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'rainbow',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-rainbow.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'colored',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-glyph-colored.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'gray',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-black-gray.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'purple-purple',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-purple-purple.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'black-white',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-black-white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-wordmark-black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Wordmark,
		style: 'purple',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-wordmark-purple-purple.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Wordmark,
		style: 'white',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-wordmark-purple-white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Wordmark,
		style: 'gray',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-wordmark-black-gray.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-portrait-black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		style: 'purple',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-portrait-purple.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		style: 'white',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-landscape-purple-white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		style: 'landscape-black',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-landscape-black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		style: 'landscape-purple',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-landscape-purple.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		style: 'gray',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-portrait-black-gray.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		style: 'landscape-gray',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-landscape-black-gray.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		style: 'portrait-purple-purple',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-portrait-purple-purple.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		style: 'landscape-purple-purple',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-landscape-purple-purple.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-portrait-black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-landscape-purple-white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'symbol',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-glyph.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-purple-white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/eth-diamond-black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-wordmark-black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-wordmark-purple-white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.LogoAndWordmark,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-logo-portrait-black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Ethereum,
		kind: IconKind.Wordmark,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://ethereum.org/images/assets/svgs/ethereum-wordmark-black.svg',
		},
	},
	/** Optimism: CDN from optimism.io/brand (OP Mainnet = chain logo; wordmark + avatar as variants) */
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://framerusercontent.com/images/Bhk5XtyRGAW86jJoFWQYE0wcWzI.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://framerusercontent.com/assets/4C7aevn7I1NA7W6ELgvkKvSKnOM.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		style: 'avatar',
		fetch: {
			fetchType: 'url',
			url: 'https://framerusercontent.com/assets/Z4dQJAxQCRUaDha5xN1AoF95g.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		style: 'chain-light',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		style: 'symbol',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Logo,
		style: 'circle-light',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/logo-circle-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Optimism,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://optimistic.etherscan.io/assets/optimism/images/svg/brandassets/wordmark-light.svg',
		},
	},
	/** XDC: xinfin.org/brand-assets (official); chain dim/dark from xdcscan.com (explorer) */
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://xinfin.org/assets/images/brand-assets/primary-icon.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://xinfin.org/assets/images/brand-assets/primary-logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'monotone-black',
		fetch: {
			fetchType: 'url',
			url: 'https://xinfin.org/assets/images/brand-assets/monotone-black-icon.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'monotone-white',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcf.cdn.prismic.io/xdcf/aCJ1SydWJ-7kR-bx_XDCIconWhiteMonoLogo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://xinfin.org/assets/images/brand-assets/inverted-primary-logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'symbol',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'chain-light',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://xinfin.org/assets/images/brand-assets/inverted-primary-icon.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://xinfin.org/assets/images/brand-assets/primary-logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.LogoAndWordmark,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Logo,
		style: 'circle-light',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/logo-circle-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcscan.com/assets/xdc/images/svg/brandassets/wordmark-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.LogoAndWordmark,
		style: 'monotone-black',
		fetch: {
			fetchType: 'url',
			url: 'https://xinfin.org/assets/images/brand-assets/monotone-black-logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.XDC,
		kind: IconKind.LogoAndWordmark,
		style: 'monotone-white',
		fetch: {
			fetchType: 'url',
			url: 'https://xdcf.cdn.prismic.io/xdcf/aCHgyidWJ-7kR7Tu_XDCPrimaryWhiteMonoLogo.svg',
		},
	},
	/** Polygon: CDN from polygon.technology/brandguidelines; GitHub 0xPolygon/polygon-token-assets assets/brandAssets (icon black/white/gradient, logo primary/monochrome, circle/square black-bg/white-bg); chain light/dim/dark + symbol/symbol-light + full logo + circle/circle-dark/circle-light/wordmark from polygonscan.com/brandassets (explorer) */
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://cdn.prod.website-files.com/637359c81e22b715cec245ad/64db31746dec8ad339c4a315_logo-light-mode.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'white',
		fetch: {
			fetchType: 'url',
			url: 'https://cdn.prod.website-files.com/637359c81e22b715cec245ad/66273f100889f2489acb2d8e_Polygon%20Logo%20Complete%20White.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'symbol',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'black',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/0xPolygon/polygon-token-assets/main/assets/brandAssets/polygon_icon_black_on_transparent.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'inverted',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/0xPolygon/polygon-token-assets/main/assets/brandAssets/polygon_icon_white_on_transparent.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'colored',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/0xPolygon/polygon-token-assets/main/assets/brandAssets/polygon_icon_gradient_on_transparent.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.LogoAndWordmark,
		style: 'colored',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/0xPolygon/polygon-token-assets/main/assets/brandAssets/polygon_logo_primary.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.LogoAndWordmark,
		style: 'monotone-black',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/0xPolygon/polygon-token-assets/main/assets/brandAssets/polygon_logo_monochrome_black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.LogoAndWordmark,
		style: 'monotone-white',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/0xPolygon/polygon-token-assets/main/assets/brandAssets/polygon_logo_monochrome_white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.LogoAndWordmark,
		style: 'white',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/0xPolygon/polygon-token-assets/main/assets/brandAssets/polygon_logo_primary_white_wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'circle-light',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/logo-circle-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'circle-black-bg',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/0xPolygon/polygon-token-assets/main/assets/brandAssets/polygon_icon_white_on_black_circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'circle-white-bg',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/0xPolygon/polygon-token-assets/main/assets/brandAssets/polygon_icon_gradient_on_white_circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'square-black-bg',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/0xPolygon/polygon-token-assets/main/assets/brandAssets/polygon_icon_white_on_black_square.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Logo,
		style: 'square-white-bg',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/0xPolygon/polygon-token-assets/main/assets/brandAssets/polygon_icon_gradient_on_white_square.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Polygon,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://polygonscan.com/assets/poly/images/svg/brandassets/wordmark-light.svg',
		},
	},
	/** ZKsync: zksync.io/brand (default + ZIP full logo); dark/light symbol from docs.zksync.io */
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://www.zksync.io/zksync-logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://docs.zksync.io/logos/zksync_logo_dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://docs.zksync.io/logos/zksync_logo_light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Logo,
		style: 'symbol',
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/images/icons/zksync-arrows.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/assets/zksync/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.zksync.io/ZKsync-Brand.zip',
			pathInZip: 'ZKsync-Brand/Logo-Primary/ZKsync-Logo-darksvg.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.LogoAndWordmark,
		style: 'white',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.zksync.io/ZKsync-Brand.zip',
			pathInZip: 'ZKsync-Brand/Logo-Primary/ZKsync-Logo-whitesvg.svg',
		},
	},
	/** ZKsync slogan assets: zksync.io/brand → ZKsync-Slogan.zip (slogan with/without bg, light/dark) */
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.LogoAndWordmark,
		style: 'slogan',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.zksync.io/ZKsync-Slogan.zip',
			pathInZip: 'zksync-slogan/slogan without bg/slogan-no-bg-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.LogoAndWordmark,
		style: 'slogan-dark',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.zksync.io/ZKsync-Slogan.zip',
			pathInZip: 'zksync-slogan/slogan without bg/slogan-no-bg-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.LogoAndWordmark,
		style: 'slogan-bg-light',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.zksync.io/ZKsync-Slogan.zip',
			pathInZip: 'zksync-slogan/slogan with bg/slogan-bg-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.LogoAndWordmark,
		style: 'slogan-bg-dark',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.zksync.io/ZKsync-Slogan.zip',
			pathInZip: 'zksync-slogan/slogan with bg/slogan-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.LogoAndWordmark,
		style: 'slogan-bg-1',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.zksync.io/ZKsync-Slogan.zip',
			pathInZip: 'zksync-slogan/slogan with bg/slogan-bg-1-logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.LogoAndWordmark,
		style: 'slogan-bg-2',
		fetch: {
			fetchType: 'zip',
			zipUrl: 'https://www.zksync.io/ZKsync-Slogan.zip',
			pathInZip: 'zksync-slogan/slogan with bg/slogan-bg-2-logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/assets/zksync/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.LogoAndWordmark,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/assets/zksync/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/assets/zksync/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/assets/zksync/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/assets/zksync/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/assets/zksync/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Logo,
		style: 'circle-light',
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/assets/zksync/images/svg/brandassets/logo-circle-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/assets/zksync/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/assets/zksync/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ZkSyncEra,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://explorer.zksync.io/assets/zksync/images/svg/brandassets/wordmark-light.svg',
		},
	},
	/** Sei: CDN from docs.sei.io/learn/general-brand-kit (symbol, full logo); chain light/dim/dark from seiscan.io (explorer) */
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://cdn.sei.io/sei.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://docs.sei.io/assets/sei-brand-assets/sei_red_and_white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Logo,
		style: 'colored',
		fetch: {
			fetchType: 'url',
			url: 'https://docs.sei.io/assets/sei-brand-assets/sei_red_symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Logo,
		style: 'symbol',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://docs.sei.io/assets/sei-brand-assets/sei_red_and_white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.LogoAndWordmark,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sei,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://seiscan.io/assets/sei/images/svg/brandassets/wordmark-light.svg',
		},
	},
	/** Avalanche: CDN from shop.avax.network (official horizontal red); chain light/dim/dark + full logo/symbol/symbol-light + logo-and-wordmark light/dark/logo + circle/circle-dark/circle-light/wordmark from snowscan.xyz (explorer) */
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://cdn.shopify.com/s/files/1/0655/7260/2081/files/AVAX_Horizontal_Red.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Logo,
		style: 'symbol',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://cdn.shopify.com/s/files/1/0655/7260/2081/files/AVAX_Horizontal_Red.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.LogoAndWordmark,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Logo,
		style: 'circle-light',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/logo-circle-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Avalanche,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://snowscan.xyz/assets/avax/images/svg/brandassets/wordmark-light.svg',
		},
	},
	/** Base: github.com/base/brand-kit (base.org/brand), logo/TheSquare/Digital */
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/base/brand-kit/main/logo/TheSquare/Digital/Base_square_blue.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'white',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/base/brand-kit/main/logo/TheSquare/Digital/Base_square_white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'black',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/base/brand-kit/main/logo/TheSquare/Digital/Base_square_black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/base/brand-kit/main/logo/Logotype/Digital/Base_lockup_black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.LogoAndWordmark,
		style: 'white',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/base/brand-kit/main/logo/Logotype/Digital/Base_lockup_white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.LogoAndWordmark,
		style: 'colored',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/base/brand-kit/main/logo/Logotype/Digital/Base_lockup_2color.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'basemark',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/base/brand-kit/main/logo/Basemark/Digital/Base_basemark_blue.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'basemark-white',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/base/brand-kit/main/logo/Basemark/Digital/Base_basemark_white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'basemark-black',
		fetch: {
			fetchType: 'url',
			url: 'https://raw.githubusercontent.com/base/brand-kit/main/logo/Basemark/Digital/Base_basemark_black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.LogoAndWordmark,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'symbol',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Logo,
		style: 'circle-light',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/logo-circle-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Base,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://basescan.org/assets/base/images/svg/brandassets/wordmark-light.svg',
		},
	},
	/** Linea: linea.build (logomark/logotype); lineascan.build/brandassets (chain light/dim/dark, full logo, symbol-light) */
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://linea.build/_next/static/media/logomark.1510dc60.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://linea.build/_next/static/media/logotype.ba0f8bdc.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'symbol',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'circle-light',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/logo-circle-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://lineascan.build/assets/linea/images/svg/brandassets/wordmark-light.svg',
		},
	},
	/** Linea official brand ZIP: linea.build/assets → Linea-Brand-Assets.zip (Logomark + Wordmark SVG variants) */
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'black',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Logo/SVG/Logomark Black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'white',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Logo/SVG/Logomark White.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Logo/SVG/Wordmark Black.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Wordmark,
		style: 'white',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Logo/SVG/Wordmark White.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'yellow-bg',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Logo/SVG/Logomark Yellow BG.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'blue-bg',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Logo/SVG/Logomark Blue BG.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'white-bg',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Logo/SVG/Logomark white BG.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Wordmark,
		style: 'yellow-bg',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Logo/SVG/Wordmark Yellow BG.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Wordmark,
		style: 'blue-bg',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Logo/SVG/Wordmark Blue BG.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Wordmark,
		style: 'white-bg',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Logo/SVG/Wordmark White BG.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'token-round',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Token/Linea-Token_Round.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Linea,
		kind: IconKind.Logo,
		style: 'token-square',
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://assets.ctfassets.net/64upluvbiuck/46y5rC2mj5Ocekur7vMSdP/c972526b87afa927a2e0bf2f506e8f75/Linea-Brand-Assets.zip',
			pathInZip: 'Linea-Brand-Assets/Token/Linea-Token_Square.svg',
		},
	},
	/** Sonic: sonicscan.org/brandassets (explorer; chain light/dim/dark + symbol, full logo; no direct SVG on official soniclabs.com) */
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Logo,
		style: 'chain-light',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Sonic,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://sonicscan.org/assets/sonic/images/svg/brandassets/wordmark-light.svg',
		},
	},
	/** Monad: monadscan.com (explorer; chain light/dim/dark + symbol, full logo; official monad.xyz/brand-and-media-kit is Figma/ZIP only) */
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Logo,
		style: 'chain-light',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Logo,
		style: 'circle-light',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/logo-circle-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Monad,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://monadscan.com/assets/monad/images/svg/brandassets/wordmark-light.svg',
		},
	},
	/** World Chain: world.org/brand (Prismic CDN lockup, wordmark, logomark); dim/dark from worldscan.org (explorer) */
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://world.org/icons/worldcoin-orb-world-logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://worldcoin-company-website.cdn.prismic.io/worldcoin-company-website/Z9GEuxsAHJWomb_3_fulllogo-1.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://worldcoin-company-website.cdn.prismic.io/worldcoin-company-website/Z9GEuxsAHJWomb_3_fulllogo-1.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.LogoAndWordmark,
		style: 'white',
		fetch: {
			fetchType: 'url',
			url: 'https://worldcoin-company-website.cdn.prismic.io/worldcoin-company-website/Z9GEwxsAHJWomb_5_fulllogo-2.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://worldcoin-company-website.cdn.prismic.io/worldcoin-company-website/Z9GEfBsAHJWomb_n_wordmark-1.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://worldcoin-company-website.cdn.prismic.io/worldcoin-company-website/Z9GEgxsAHJWomb_q_wordmark-2.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		style: 'logomark-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://worldcoin-company-website.cdn.prismic.io/worldcoin-company-website/Z9GEWBsAHJWomb_i_logomark-1.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		style: 'logomark-light',
		fetch: {
			fetchType: 'url',
			url: 'https://worldcoin-company-website.cdn.prismic.io/worldcoin-company-website/Z9GEYBsAHJWomb_k_logomark-2.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/brandassets/wordmark-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		style: 'symbol',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.WorldChain,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://worldscan.org/assets/world/images/svg/brandassets/logo-light.svg',
		},
	},
	/** Celo: celoscan.io/brandassets (explorer; chain light/dim/dark + symbol, full logo; official celo.org/brand-kit is Drive/ZIP only) */
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Logo,
		style: 'chain-light',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Logo,
		style: 'circle-light',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/logo-circle-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Celo,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://celoscan.io/assets/celo/images/svg/brandassets/wordmark-light.svg',
		},
	},
	/** Arbitrum: arbitrum.io (arb_logo_color, assets/arbitrum/logo_color, brandkit/icon_white); default/symbol/light/chain-light/dim/dark from arbiscan.io (explorer; chain light/dim/dark + full logo) */
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://arbitrum.io/arb_logo_color.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'colored',
		fetch: {
			fetchType: 'url',
			url: 'https://arbitrum.io/assets/arbitrum/logo_color.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'white',
		fetch: {
			fetchType: 'url',
			url: 'https://arbitrum.io/brandkit/icon_white.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'chain-light',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.LogoAndWordmark,
		style: 'alt',
		fetch: {
			fetchType: 'url',
			url: 'https://www.arbitrumhub.io/brandAndPress/brand.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Logo,
		style: 'circle-light',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/logo-circle-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Arbitrum,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://arbiscan.io/assets/arbitrum/images/svg/brandassets/wordmark-light.svg',
		},
	},
	/** Codex: docs.codex.xyz (Astro); codex.io/press-kit CDN (colour + monochrome SVG); ZIP from GitHub (LogoAndWordmark chartreuse bg) */
	{ target: 'chain' as const,
		id: ChainId.Codex,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://docs.codex.xyz/_astro/codex-dark-full-logo.IOPtxPup.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Codex,
		kind: IconKind.Logo,
		style: 'white',
		fetch: {
			fetchType: 'url',
			url: 'https://docs.codex.xyz/_astro/codex-white-full-logo.CI7DkyOz.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Codex,
		kind: IconKind.Logo,
		style: 'colored',
		fetch: {
			fetchType: 'url',
			url: 'https://cdn.prod.website-files.com/6669befdbe2926bfc0a8363a/667ed94e03b6f717805e8363_Logo-pack-colour.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Codex,
		kind: IconKind.Logo,
		style: 'monotone-black',
		fetch: {
			fetchType: 'url',
			url: 'https://cdn.prod.website-files.com/6669befdbe2926bfc0a8363a/667ed94e9a8f19f44946fdee_Logo-pack-bw.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.Codex,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'zip',
			zipUrl:
				'https://cdn.jsdelivr.net/gh/MadeByKin/codex/codex%20brand%20assets%20%E2%80%94%20color.zip',
			pathInZip:
				'codex brand assets \u00e2\u0080\u0094 color/codex logo black, chartreuse bg.svg',
		},
	},
	/** Arc Testnet: CDN from Alchemy (default icon); official Arc brand at arc.link/newsroom/brand-assets (PNG — Powered by ARC dark/light/colored/alt) */
	{ target: 'chain' as const,
		id: ChainId.ArcTestnet,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://static.alchemyapi.io/images/emblems/arc-testnet.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ArcTestnet,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'png',
			url: 'https://arc-prd.s3.us-east-2.amazonaws.com/storage/static/logos/1.png',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ArcTestnet,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'png',
			url: 'https://arc-prd.s3.us-east-2.amazonaws.com/storage/static/logos/2.png',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ArcTestnet,
		kind: IconKind.LogoAndWordmark,
		style: 'colored',
		fetch: {
			fetchType: 'png',
			url: 'https://arc-prd.s3.us-east-2.amazonaws.com/storage/static/logos/3.png',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.ArcTestnet,
		kind: IconKind.LogoAndWordmark,
		style: 'alt',
		fetch: {
			fetchType: 'png',
			url: 'https://arc-prd.s3.us-east-2.amazonaws.com/storage/static/logos/6.png',
		},
	},
	/** HyperEVM: hyperevmscan.io/brandassets (explorer; chain light/dim/dark + full logo, symbol, logo-light, symbol-light) */
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Logo,
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/logos/chain-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Logo,
		style: 'logo',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Logo,
		style: 'symbol',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/logo-symbol.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Logo,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Logo,
		style: 'dim',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/logos/chain-dim.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Logo,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/logos/chain-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.LogoAndWordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/logo.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.LogoAndWordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/logo-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.LogoAndWordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/logo-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Logo,
		style: 'symbol-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/logo-symbol-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Logo,
		style: 'circle',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/logo-circle.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Logo,
		style: 'circle-dark',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/logo-circle-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Logo,
		style: 'circle-light',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/logo-circle-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Wordmark,
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/wordmark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Wordmark,
		style: 'dark',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/wordmark-dark.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Wordmark,
		style: 'light',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/wordmark-light.svg',
		},
	},
	{ target: 'chain' as const,
		id: ChainId.HyperEVM,
		kind: IconKind.Logo,
		style: 'symbol-light',
		fetch: {
			fetchType: 'url',
			url: 'https://hyperevmscan.io/assets/hype/images/svg/brandassets/logo-symbol-light.svg',
		},
	},
] as const satisfies readonly IconFetchItem[]

/** Testnet reuse mainnet default icon. */
export const chainIconAliases = [
	{ target: 'chain' as const, fromId: ChainId.XDCApothem, toId: ChainId.XDC },
	{ target: 'chain' as const, fromId: ChainId.UnichainSepolia, toId: ChainId.Unichain },
	{ target: 'chain' as const, fromId: ChainId.PolygonAmoy, toId: ChainId.Polygon },
	{ target: 'chain' as const, fromId: ChainId.MonadTestnet, toId: ChainId.Monad },
	{ target: 'chain' as const, fromId: ChainId.SonicTestnet, toId: ChainId.Sonic },
	{ target: 'chain' as const, fromId: ChainId.ZkSyncEraSepolia, toId: ChainId.ZkSyncEra },
	{ target: 'chain' as const, fromId: ChainId.WorldChainSepolia, toId: ChainId.WorldChain },
	{ target: 'chain' as const, fromId: ChainId.HyperEVMTestnet, toId: ChainId.HyperEVM },
	{ target: 'chain' as const, fromId: ChainId.SeiTestnet, toId: ChainId.Sei },
	{ target: 'chain' as const, fromId: ChainId.ArbitrumSepolia, toId: ChainId.Arbitrum },
	{ target: 'chain' as const, fromId: ChainId.CeloSepolia, toId: ChainId.Celo },
	{ target: 'chain' as const, fromId: ChainId.AvalancheFuji, toId: ChainId.Avalanche },
	{ target: 'chain' as const, fromId: ChainId.BaseSepolia, toId: ChainId.Base },
	{ target: 'chain' as const, fromId: ChainId.LineaSepolia, toId: ChainId.Linea },
	{ target: 'chain' as const, fromId: ChainId.InkTestnet, toId: ChainId.Ink },
	{ target: 'chain' as const, fromId: ChainId.CodexTestnet, toId: ChainId.Codex },
	{ target: 'chain' as const, fromId: ChainId.PlumeTestnet, toId: ChainId.Plume },
	{ target: 'chain' as const, fromId: ChainId.EthereumSepolia, toId: ChainId.Ethereum },
	{ target: 'chain' as const, fromId: ChainId.OPSepolia, toId: ChainId.Optimism },
] as const satisfies readonly IconAlias[]