/**
 * TanStack DB collection ids and profile-scoped storage keys.
 * TitleCase enum values used for both collection `id` and localStorage `storageKey`.
 */

/** Profile-scoped localStorage key for persistent room peer id (not a TanStack collection). */
export const ROOM_PERSISTENT_PEER_ID_STORAGE_KEY = 'RoomPersistentPeerId'

export enum CollectionId {
	ActorAllowances = 'ActorAllowances',
	ActorCoins = 'ActorCoins',
	Actors = 'Actors',
	AgentChatTrees = 'AgentChatTrees',
	AgentChatTurns = 'AgentChatTurns',
	Blocks = 'Blocks',
	BridgeRouteItems = 'BridgeRouteItems',
	BridgeRoutes = 'BridgeRoutes',
	BridgeTransactions = 'BridgeTransactions',
	NetworkTransactions = 'NetworkTransactions',
	Coins = 'Coins',
	CctpAllowance = 'CctpAllowance',
	CctpFees = 'CctpFees',
	Dashboards = 'Dashboards',
	EntitySources = 'EntitySources',
	EvmActorProfiles = 'EvmActorProfiles',
	IdentityLinks = 'IdentityLinks',
	LlmConnections = 'LlmConnections',
	MyPeerIds = 'MyPeerIds',
	Networks = 'Networks',
	PartykitRoomPeers = 'PartykitRoomPeers',
	PartykitRooms = 'PartykitRooms',
	SharedAddresses = 'SharedAddresses',
	SiweChallenges = 'SiweChallenges',
	StorkPrices = 'StorkPrices',
	SwapQuotes = 'SwapQuotes',
	TokenListCoins = 'TokenListCoins',
	SessionActionTransactionSimulations = 'SessionActionTransactionSimulations',
	SessionActionTransactions = 'SessionActionTransactions',
	SessionActions = 'SessionActions',
	SessionSimulations = 'SessionSimulations',
	Sessions = 'Sessions',
	TransferEvents = 'TransferEvents',
	TransferGraphs = 'TransferGraphs',
	TransferRequests = 'TransferRequests',
	UniswapPositions = 'UniswapPositions',
	UniswapPools = 'UniswapPools',
	SiweVerifications = 'SiweVerifications',
	WalletConnections = 'WalletConnections',
	Wallets = 'Wallets',
	WatchedEntities = 'WatchedEntities',
	StateChannelStates = 'StateChannelStates',
	StateChannels = 'StateChannels',
	StateChannelDeposits = 'StateChannelDeposits',
	StateChannelTransfers = 'StateChannelTransfers',
}
