/**
 * TanStack DB collection ids and profile-scoped storage keys.
 * TitleCase enum values used for both collection `id` and localStorage `storageKey`.
 */

export enum CollectionId {
	ActorAllowances = 'ActorAllowances',
	ActorCoins = 'ActorCoins',
	Actors = 'Actors',
	AgentChatTrees = 'AgentChatTrees',
	AgentChatTurns = 'AgentChatTurns',
	Blocks = 'Blocks',
	BridgeRouteItems = 'BridgeRouteItems',
	BridgeRoutes = 'BridgeRoutes',
	BridgeTransactions = 'BridgeTransactions',
	ChainTransactions = 'ChainTransactions',
	Coins = 'Coins',
	CctpAllowance = 'CctpAllowance',
	CctpFees = 'CctpFees',
	DashboardPanels = 'DashboardPanels',
	EntitySources = 'EntitySources',
	EvmActorProfiles = 'EvmActorProfiles',
	IdentityResolution = 'IdentityResolution',
	LlmConnections = 'LlmConnections',
	MyPeerIds = 'MyPeerIds',
	Networks = 'Networks',
	RoomPeers = 'RoomPeers',
	RoomPersistentPeerId = 'RoomPersistentPeerId',
	Rooms = 'Rooms',
	SharedAddresses = 'SharedAddresses',
	SiweChallenges = 'SiweChallenges',
	StorkPrices = 'StorkPrices',
	SwapQuotes = 'SwapQuotes',
	TokenListCoins = 'TokenListCoins',
	TransactionSessionSimulations = 'TransactionSessionSimulations',
	TransactionSessions = 'TransactionSessions',
	Transactions = 'Transactions',
	TransferEvents = 'TransferEvents',
	TransferGraphs = 'TransferGraphs',
	TransferRequests = 'TransferRequests',
	UniswapPositions = 'UniswapPositions',
	UniswapPools = 'UniswapPools',
	Verifications = 'Verifications',
	WalletConnections = 'WalletConnections',
	Wallets = 'Wallets',
	WatchedEntities = 'WatchedEntities',
	YellowChannelStates = 'YellowChannelStates',
	YellowChannels = 'YellowChannels',
	YellowDeposits = 'YellowDeposits',
	YellowTransfers = 'YellowTransfers',
}
