/**
 * Room display name word lists for human-friendly room codes.
 */

export type RoomLandmarkEntry = {
	landmark: string
}

export const adjectives = [
	{ adjective: 'Ancient' },
	{ adjective: 'Bright' },
	{ adjective: 'Calm' },
	{ adjective: 'Clear' },
	{ adjective: 'Cool' },
	{ adjective: 'Deep' },
	{ adjective: 'Distant' },
	{ adjective: 'Emerald' },
	{ adjective: 'Foggy' },
	{ adjective: 'Fresh' },
	{ adjective: 'Hidden' },
	{ adjective: 'High' },
	{ adjective: 'Hollow' },
	{ adjective: 'Icy' },
	{ adjective: 'Lone' },
	{ adjective: 'Low' },
	{ adjective: 'Misty' },
	{ adjective: 'Narrow' },
	{ adjective: 'Old' },
	{ adjective: 'Open' },
	{ adjective: 'Peaceful' },
	{ adjective: 'Quiet' },
	{ adjective: 'Remote' },
	{ adjective: 'Rocky' },
	{ adjective: 'Rustic' },
	{ adjective: 'Sandy' },
	{ adjective: 'Secret' },
	{ adjective: 'Shadow' },
	{ adjective: 'Shallow' },
	{ adjective: 'Silent' },
	{ adjective: 'Snowy' },
	{ adjective: 'Steep' },
	{ adjective: 'Still' },
	{ adjective: 'Stormy' },
	{ adjective: 'Sunny' },
	{ adjective: 'Vast' },
	{ adjective: 'Verdant' },
	{ adjective: 'Warm' },
	{ adjective: 'Wide' },
	{ adjective: 'Windy' },
	{ adjective: 'Wooded' },
] as const

export const adjectivesByIndex = Object.fromEntries(
	adjectives.map((entry, index) => [index, entry]),
)

export const nouns = [
	{ noun: 'Academy', icon: '🏫' },
	{ noun: 'Arena', icon: '🏟️' },
	{ noun: 'Bay', icon: '🌊' },
	{ noun: 'Beach', icon: '🏖️' },
	{ noun: 'Bridge', icon: '🌉' },
	{ noun: 'Camp', icon: '⛺' },
	{ noun: 'Canyon', icon: '🏜️' },
	{ noun: 'Castle', icon: '🏰' },
	{ noun: 'Cave', icon: '🪨' },
	{ noun: 'Cottage', icon: '🏡' },
	{ noun: 'Depot', icon: '🚂' },
	{ noun: 'Dock', icon: '🚢' },
	{ noun: 'Factory', icon: '🏭' },
	{ noun: 'Field', icon: '🌾' },
	{ noun: 'Forest', icon: '🌲' },
	{ noun: 'Fountain', icon: '⛲' },
	{ noun: 'Garden', icon: '🌿' },
	{ noun: 'Grove', icon: '🌳' },
	{ noun: 'Hall', icon: '🏛️' },
	{ noun: 'Harbor', icon: '⚓' },
	{ noun: 'Hut', icon: '🛖' },
	{ noun: 'Inn', icon: '🏨' },
	{ noun: 'Island', icon: '🏝️' },
	{ noun: 'Library', icon: '📚' },
	{ noun: 'Market', icon: '🏪' },
	{ noun: 'Meadow', icon: '🌼' },
	{ noun: 'Monument', icon: '🗿' },
	{ noun: 'Mountain', icon: '🏔️' },
	{ noun: 'Oasis', icon: '🌴' },
	{ noun: 'Park', icon: '🏞️' },
	{ noun: 'Pavilion', icon: '🏯' },
	{ noun: 'Peak', icon: '🗻' },
	{ noun: 'Pier', icon: '⛵' },
	{ noun: 'Plaza', icon: '🏬' },
	{ noun: 'Post', icon: '🏤' },
	{ noun: 'Railway', icon: '🛤️' },
	{ noun: 'Reef', icon: '🪸' },
	{ noun: 'Road', icon: '🛣️' },
	{ noun: 'Ruins', icon: '🏚️' },
	{ noun: 'Station', icon: '🚉' },
	{ noun: 'Theater', icon: '🎭' },
	{ noun: 'Tower', icon: '🗼' },
	{ noun: 'Village', icon: '🏘️' },
	{ noun: 'Vista', icon: '🌄' },
	{ noun: 'Volcano', icon: '🌋' },
] as const

export const nounsByIndex = Object.fromEntries(
	nouns.map((entry, index) => [index, entry]),
)
