/**
 * EVM opcode metadata. Source: evm.codes opcodes.json, ethereum.org opcodes.
 * How to refresh: fetch https://raw.githubusercontent.com/duneanalytics/evm.codes/main/opcodes.json
 */

import { EvmOpcode } from '$/constants/opcodes/types.ts'
import type { OpcodeEntry } from '$/constants/opcodes/types.ts'

export const opcodeEntries: Record<EvmOpcode, OpcodeEntry> = {
	[EvmOpcode.STOP]: { mnemonic: 'STOP', input: '', output: '', description: 'Halts execution' },
	[EvmOpcode.ADD]: { mnemonic: 'ADD', input: 'a | b', output: 'a + b', description: 'Addition operation' },
	[EvmOpcode.MUL]: { mnemonic: 'MUL', input: 'a | b', output: 'a * b', description: 'Multiplication operation' },
	[EvmOpcode.SUB]: { mnemonic: 'SUB', input: 'a | b', output: 'a - b', description: 'Subtraction operation' },
	[EvmOpcode.DIV]: { mnemonic: 'DIV', input: 'a | b', output: 'a // b', description: 'Integer division operation' },
	[EvmOpcode.SDIV]: { mnemonic: 'SDIV', input: 'a | b', output: 'a // b', description: 'Signed integer division operation' },
	[EvmOpcode.MOD]: { mnemonic: 'MOD', input: 'a | b', output: 'a % b', description: 'Modulo remainder operation' },
	[EvmOpcode.SMOD]: { mnemonic: 'SMOD', input: 'a | b', output: 'a % b', description: 'Signed modulo remainder operation' },
	[EvmOpcode.ADDMOD]: { mnemonic: 'ADDMOD', input: 'a | b | N', output: '(a + b) % N', description: 'Modulo addition operation' },
	[EvmOpcode.MULMOD]: { mnemonic: 'MULMOD', input: 'a | b | N', output: '(a * b) % N', description: 'Modulo multiplication operation' },
	[EvmOpcode.EXP]: { mnemonic: 'EXP', input: 'a | exponent', output: 'a ** exponent', description: 'Exponential operation' },
	[EvmOpcode.SIGNEXTEND]: { mnemonic: 'SIGNEXTEND', input: 'b | x', output: 'y', description: 'Extend length of two\'s complement signed integer' },
	[EvmOpcode.LT]: { mnemonic: 'LT', input: 'a | b', output: 'a < b', description: 'Less-than comparison' },
	[EvmOpcode.GT]: { mnemonic: 'GT', input: 'a | b', output: 'a > b', description: 'Greater-than comparison' },
	[EvmOpcode.SLT]: { mnemonic: 'SLT', input: 'a | b', output: 'a < b', description: 'Signed less-than comparison' },
	[EvmOpcode.SGT]: { mnemonic: 'SGT', input: 'a | b', output: 'a > b', description: 'Signed greater-than comparison' },
	[EvmOpcode.EQ]: { mnemonic: 'EQ', input: 'a | b', output: 'a == b', description: 'Equality comparison' },
	[EvmOpcode.ISZERO]: { mnemonic: 'ISZERO', input: 'a', output: 'a == 0', description: 'Is-zero comparison' },
	[EvmOpcode.AND]: { mnemonic: 'AND', input: 'a | b', output: 'a & b', description: 'Bitwise AND operation' },
	[EvmOpcode.OR]: { mnemonic: 'OR', input: 'a | b', output: 'a | b', description: 'Bitwise OR operation' },
	[EvmOpcode.XOR]: { mnemonic: 'XOR', input: 'a | b', output: 'a ^ b', description: 'Bitwise XOR operation' },
	[EvmOpcode.NOT]: { mnemonic: 'NOT', input: 'a', output: '~a', description: 'Bitwise NOT operation' },
	[EvmOpcode.BYTE]: { mnemonic: 'BYTE', input: 'i | x', output: 'y', description: 'Retrieve single byte from word' },
	[EvmOpcode.SHL]: { mnemonic: 'SHL', input: 'shift | value', output: 'value << shift', description: 'Left shift operation' },
	[EvmOpcode.SHR]: { mnemonic: 'SHR', input: 'shift | value', output: 'value >> shift', description: 'Logical right shift operation' },
	[EvmOpcode.SAR]: { mnemonic: 'SAR', input: 'shift | value', output: 'value >> shift', description: 'Arithmetic (signed) right shift operation' },
	[EvmOpcode.CLZ]: { mnemonic: 'CLZ', input: 'x', output: 'clz(x)', description: 'Count leading zero bits' },
	[EvmOpcode.KECCAK256]: { mnemonic: 'KECCAK256', input: 'offset | size', output: 'hash', description: 'Compute Keccak-256 hash' },
	[EvmOpcode.ADDRESS]: { mnemonic: 'ADDRESS', input: '', output: 'address(this)', description: 'Address of executing contract' },
	[EvmOpcode.BALANCE]: { mnemonic: 'BALANCE', input: 'addr', output: 'balance', description: 'Get balance of address' },
	[EvmOpcode.ORIGIN]: { mnemonic: 'ORIGIN', input: '', output: 'tx.origin', description: 'Address that originated the tx' },
	[EvmOpcode.CALLER]: { mnemonic: 'CALLER', input: '', output: 'msg.sender', description: 'Address of msg sender' },
	[EvmOpcode.CALLVALUE]: { mnemonic: 'CALLVALUE', input: '', output: 'msg.value', description: 'Msg value in wei' },
	[EvmOpcode.CALLDATALOAD]: { mnemonic: 'CALLDATALOAD', input: 'idx', output: 'word', description: 'Read word from calldata at index' },
	[EvmOpcode.CALLDATASIZE]: { mnemonic: 'CALLDATASIZE', input: '', output: 'size', description: 'Length of calldata in bytes' },
	[EvmOpcode.CALLDATACOPY]: { mnemonic: 'CALLDATACOPY', input: 'dstOst | ost | len', output: '', description: 'Copy calldata to memory' },
	[EvmOpcode.CODESIZE]: { mnemonic: 'CODESIZE', input: '', output: 'size', description: 'Length of executing contract code' },
	[EvmOpcode.CODECOPY]: { mnemonic: 'CODECOPY', input: 'dstOst | ost | len', output: '', description: 'Copy code to memory' },
	[EvmOpcode.GASPRICE]: { mnemonic: 'GASPRICE', input: '', output: 'gasprice', description: 'Gas price of tx' },
	[EvmOpcode.EXTCODESIZE]: { mnemonic: 'EXTCODESIZE', input: 'addr', output: 'size', description: 'Size of code at address' },
	[EvmOpcode.EXTCODECOPY]: { mnemonic: 'EXTCODECOPY', input: 'addr | dstOst | ost | len', output: '', description: 'Copy code from address to memory' },
	[EvmOpcode.RETURNDATASIZE]: { mnemonic: 'RETURNDATASIZE', input: '', output: 'size', description: 'Size of returned data from last call' },
	[EvmOpcode.RETURNDATACOPY]: { mnemonic: 'RETURNDATACOPY', input: 'dstOst | ost | len', output: '', description: 'Copy return data to memory' },
	[EvmOpcode.EXTCODEHASH]: { mnemonic: 'EXTCODEHASH', input: 'addr', output: 'hash', description: 'Keccak256 hash of code at address' },
	[EvmOpcode.BLOCKHASH]: { mnemonic: 'BLOCKHASH', input: 'blockNum', output: 'hash', description: 'Hash of block number' },
	[EvmOpcode.COINBASE]: { mnemonic: 'COINBASE', input: '', output: 'block.coinbase', description: 'Address of block proposer' },
	[EvmOpcode.TIMESTAMP]: { mnemonic: 'TIMESTAMP', input: '', output: 'block.timestamp', description: 'Timestamp of current block' },
	[EvmOpcode.NUMBER]: { mnemonic: 'NUMBER', input: '', output: 'block.number', description: 'Number of current block' },
	[EvmOpcode.PREVRANDAO]: { mnemonic: 'PREVRANDAO', input: '', output: 'randomness', description: 'Randomness beacon' },
	[EvmOpcode.GASLIMIT]: { mnemonic: 'GASLIMIT', input: '', output: 'block.gaslimit', description: 'Gas limit of current block' },
	[EvmOpcode.CHAINID]: { mnemonic: 'CHAINID', input: '', output: 'chain_id', description: 'Current chain id' },
	[EvmOpcode.SELFBALANCE]: { mnemonic: 'SELFBALANCE', input: '', output: 'balance', description: 'Balance of executing contract' },
	[EvmOpcode.BASEFEE]: { mnemonic: 'BASEFEE', input: '', output: 'block.basefee', description: 'Base fee of current block' },
	[EvmOpcode.BLOBHASH]: { mnemonic: 'BLOBHASH', input: 'idx', output: 'hash', description: 'Blob versioned hash at index' },
	[EvmOpcode.BLOBBASEFEE]: { mnemonic: 'BLOBBASEFEE', input: '', output: 'block.blobbasefee', description: 'Blob base fee of current block' },
	[EvmOpcode.POP]: { mnemonic: 'POP', input: '_', output: '', description: 'Remove top of stack' },
	[EvmOpcode.MLOAD]: { mnemonic: 'MLOAD', input: 'ost', output: 'word', description: 'Load word from memory' },
	[EvmOpcode.MSTORE]: { mnemonic: 'MSTORE', input: 'ost | val', output: '', description: 'Store word to memory' },
	[EvmOpcode.MSTORE8]: { mnemonic: 'MSTORE8', input: 'ost | val', output: '', description: 'Store byte to memory' },
	[EvmOpcode.SLOAD]: { mnemonic: 'SLOAD', input: 'key', output: 'value', description: 'Load word from storage' },
	[EvmOpcode.SSTORE]: { mnemonic: 'SSTORE', input: 'key | val', output: '', description: 'Store word to storage' },
	[EvmOpcode.JUMP]: { mnemonic: 'JUMP', input: 'dst', output: '', description: 'Jump to destination' },
	[EvmOpcode.JUMPI]: { mnemonic: 'JUMPI', input: 'dst | condition', output: '', description: 'Conditional jump' },
	[EvmOpcode.PC]: { mnemonic: 'PC', input: '', output: 'pc', description: 'Program counter' },
	[EvmOpcode.MSIZE]: { mnemonic: 'MSIZE', input: '', output: 'size', description: 'Size of memory in bytes' },
	[EvmOpcode.GAS]: { mnemonic: 'GAS', input: '', output: 'remaining', description: 'Remaining gas' },
	[EvmOpcode.JUMPDEST]: { mnemonic: 'JUMPDEST', input: '', output: '', description: 'Mark valid jump destination' },
	[EvmOpcode.TLOAD]: { mnemonic: 'TLOAD', input: 'key', output: 'value', description: 'Load from transient storage' },
	[EvmOpcode.TSTORE]: { mnemonic: 'TSTORE', input: 'key | value', output: '', description: 'Store to transient storage' },
	[EvmOpcode.MCOPY]: { mnemonic: 'MCOPY', input: 'dstOst | ost | len', output: '', description: 'Copy memory areas' },
	[EvmOpcode.PUSH0]: { mnemonic: 'PUSH0', input: '', output: '0', description: 'Push 0 onto stack' },
	[EvmOpcode.PUSH1]: { mnemonic: 'PUSH1', input: '', output: 'uint8', description: 'Push 1-byte value' },
	[EvmOpcode.PUSH2]: { mnemonic: 'PUSH2', input: '', output: 'uint16', description: 'Push 2-byte value' },
	[EvmOpcode.PUSH3]: { mnemonic: 'PUSH3', input: '', output: 'uint24', description: 'Push 3-byte value' },
	[EvmOpcode.PUSH4]: { mnemonic: 'PUSH4', input: '', output: 'uint32', description: 'Push 4-byte value' },
	[EvmOpcode.PUSH5]: { mnemonic: 'PUSH5', input: '', output: 'uint40', description: 'Push 5-byte value' },
	[EvmOpcode.PUSH6]: { mnemonic: 'PUSH6', input: '', output: 'uint48', description: 'Push 6-byte value' },
	[EvmOpcode.PUSH7]: { mnemonic: 'PUSH7', input: '', output: 'uint56', description: 'Push 7-byte value' },
	[EvmOpcode.PUSH8]: { mnemonic: 'PUSH8', input: '', output: 'uint64', description: 'Push 8-byte value' },
	[EvmOpcode.PUSH9]: { mnemonic: 'PUSH9', input: '', output: 'uint72', description: 'Push 9-byte value' },
	[EvmOpcode.PUSH10]: { mnemonic: 'PUSH10', input: '', output: 'uint80', description: 'Push 10-byte value' },
	[EvmOpcode.PUSH11]: { mnemonic: 'PUSH11', input: '', output: 'uint88', description: 'Push 11-byte value' },
	[EvmOpcode.PUSH12]: { mnemonic: 'PUSH12', input: '', output: 'uint96', description: 'Push 12-byte value' },
	[EvmOpcode.PUSH13]: { mnemonic: 'PUSH13', input: '', output: 'uint104', description: 'Push 13-byte value' },
	[EvmOpcode.PUSH14]: { mnemonic: 'PUSH14', input: '', output: 'uint112', description: 'Push 14-byte value' },
	[EvmOpcode.PUSH15]: { mnemonic: 'PUSH15', input: '', output: 'uint120', description: 'Push 15-byte value' },
	[EvmOpcode.PUSH16]: { mnemonic: 'PUSH16', input: '', output: 'uint128', description: 'Push 16-byte value' },
	[EvmOpcode.PUSH17]: { mnemonic: 'PUSH17', input: '', output: 'uint136', description: 'Push 17-byte value' },
	[EvmOpcode.PUSH18]: { mnemonic: 'PUSH18', input: '', output: 'uint144', description: 'Push 18-byte value' },
	[EvmOpcode.PUSH19]: { mnemonic: 'PUSH19', input: '', output: 'uint152', description: 'Push 19-byte value' },
	[EvmOpcode.PUSH20]: { mnemonic: 'PUSH20', input: '', output: 'uint160', description: 'Push 20-byte value' },
	[EvmOpcode.PUSH21]: { mnemonic: 'PUSH21', input: '', output: 'uint168', description: 'Push 21-byte value' },
	[EvmOpcode.PUSH22]: { mnemonic: 'PUSH22', input: '', output: 'uint176', description: 'Push 22-byte value' },
	[EvmOpcode.PUSH23]: { mnemonic: 'PUSH23', input: '', output: 'uint184', description: 'Push 23-byte value' },
	[EvmOpcode.PUSH24]: { mnemonic: 'PUSH24', input: '', output: 'uint192', description: 'Push 24-byte value' },
	[EvmOpcode.PUSH25]: { mnemonic: 'PUSH25', input: '', output: 'uint200', description: 'Push 25-byte value' },
	[EvmOpcode.PUSH26]: { mnemonic: 'PUSH26', input: '', output: 'uint208', description: 'Push 26-byte value' },
	[EvmOpcode.PUSH27]: { mnemonic: 'PUSH27', input: '', output: 'uint216', description: 'Push 27-byte value' },
	[EvmOpcode.PUSH28]: { mnemonic: 'PUSH28', input: '', output: 'uint224', description: 'Push 28-byte value' },
	[EvmOpcode.PUSH29]: { mnemonic: 'PUSH29', input: '', output: 'uint232', description: 'Push 29-byte value' },
	[EvmOpcode.PUSH30]: { mnemonic: 'PUSH30', input: '', output: 'uint240', description: 'Push 30-byte value' },
	[EvmOpcode.PUSH31]: { mnemonic: 'PUSH31', input: '', output: 'uint248', description: 'Push 31-byte value' },
	[EvmOpcode.PUSH32]: { mnemonic: 'PUSH32', input: '', output: 'uint256', description: 'Push 32-byte value' },
	[EvmOpcode.DUP1]: { mnemonic: 'DUP1', input: 'a', output: 'a | a', description: 'Clone 1st value on stack' },
	[EvmOpcode.DUP2]: { mnemonic: 'DUP2', input: '_, a', output: 'a, _, a', description: 'Clone 2nd value on stack' },
	[EvmOpcode.DUP3]: { mnemonic: 'DUP3', input: '_, _, a', output: 'a, _, _, a', description: 'Clone 3rd value on stack' },
	[EvmOpcode.DUP4]: { mnemonic: 'DUP4', input: '_, _, _, a', output: 'a, _, _, _, a', description: 'Clone 4th value on stack' },
	[EvmOpcode.DUP5]: { mnemonic: 'DUP5', input: '..., a', output: 'a, ..., a', description: 'Clone 5th value on stack' },
	[EvmOpcode.DUP6]: { mnemonic: 'DUP6', input: '..., a', output: 'a, ..., a', description: 'Clone 6th value on stack' },
	[EvmOpcode.DUP7]: { mnemonic: 'DUP7', input: '..., a', output: 'a, ..., a', description: 'Clone 7th value on stack' },
	[EvmOpcode.DUP8]: { mnemonic: 'DUP8', input: '..., a', output: 'a, ..., a', description: 'Clone 8th value on stack' },
	[EvmOpcode.DUP9]: { mnemonic: 'DUP9', input: '..., a', output: 'a, ..., a', description: 'Clone 9th value on stack' },
	[EvmOpcode.DUP10]: { mnemonic: 'DUP10', input: '..., a', output: 'a, ..., a', description: 'Clone 10th value on stack' },
	[EvmOpcode.DUP11]: { mnemonic: 'DUP11', input: '..., a', output: 'a, ..., a', description: 'Clone 11th value on stack' },
	[EvmOpcode.DUP12]: { mnemonic: 'DUP12', input: '..., a', output: 'a, ..., a', description: 'Clone 12th value on stack' },
	[EvmOpcode.DUP13]: { mnemonic: 'DUP13', input: '..., a', output: 'a, ..., a', description: 'Clone 13th value on stack' },
	[EvmOpcode.DUP14]: { mnemonic: 'DUP14', input: '..., a', output: 'a, ..., a', description: 'Clone 14th value on stack' },
	[EvmOpcode.DUP15]: { mnemonic: 'DUP15', input: '..., a', output: 'a, ..., a', description: 'Clone 15th value on stack' },
	[EvmOpcode.DUP16]: { mnemonic: 'DUP16', input: '..., a', output: 'a, ..., a', description: 'Clone 16th value on stack' },
	[EvmOpcode.SWAP1]: { mnemonic: 'SWAP1', input: 'a, b', output: 'b, a', description: 'Swap 1st and 2nd' },
	[EvmOpcode.SWAP2]: { mnemonic: 'SWAP2', input: 'a, _, b', output: 'b, _, a', description: 'Swap 1st and 3rd' },
	[EvmOpcode.SWAP3]: { mnemonic: 'SWAP3', input: 'a, _, _, b', output: 'b, _, _, a', description: 'Swap 1st and 4th' },
	[EvmOpcode.SWAP4]: { mnemonic: 'SWAP4', input: 'a, _, _, _, b', output: 'b, _, _, _, a', description: 'Swap 1st and 5th' },
	[EvmOpcode.SWAP5]: { mnemonic: 'SWAP5', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 6th' },
	[EvmOpcode.SWAP6]: { mnemonic: 'SWAP6', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 7th' },
	[EvmOpcode.SWAP7]: { mnemonic: 'SWAP7', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 8th' },
	[EvmOpcode.SWAP8]: { mnemonic: 'SWAP8', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 9th' },
	[EvmOpcode.SWAP9]: { mnemonic: 'SWAP9', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 10th' },
	[EvmOpcode.SWAP10]: { mnemonic: 'SWAP10', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 11th' },
	[EvmOpcode.SWAP11]: { mnemonic: 'SWAP11', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 12th' },
	[EvmOpcode.SWAP12]: { mnemonic: 'SWAP12', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 13th' },
	[EvmOpcode.SWAP13]: { mnemonic: 'SWAP13', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 14th' },
	[EvmOpcode.SWAP14]: { mnemonic: 'SWAP14', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 15th' },
	[EvmOpcode.SWAP15]: { mnemonic: 'SWAP15', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 16th' },
	[EvmOpcode.SWAP16]: { mnemonic: 'SWAP16', input: 'a, ..., b', output: 'b, ..., a', description: 'Swap 1st and 17th' },
	[EvmOpcode.LOG0]: { mnemonic: 'LOG0', input: 'offset | size', output: '', description: 'Append log with no topics' },
	[EvmOpcode.LOG1]: { mnemonic: 'LOG1', input: 'offset | size | topic', output: '', description: 'Append log with one topic' },
	[EvmOpcode.LOG2]: { mnemonic: 'LOG2', input: 'offset | size | topic1 | topic2', output: '', description: 'Append log with two topics' },
	[EvmOpcode.LOG3]: { mnemonic: 'LOG3', input: 'offset | size | topic1 | topic2 | topic3', output: '', description: 'Append log with three topics' },
	[EvmOpcode.LOG4]: { mnemonic: 'LOG4', input: 'offset | size | topic1 | topic2 | topic3 | topic4', output: '', description: 'Append log with four topics' },
	[EvmOpcode.CREATE]: { mnemonic: 'CREATE', input: 'val | ost | len', output: 'addr', description: 'Create new contract' },
	[EvmOpcode.CALL]: { mnemonic: 'CALL', input: 'gas | addr | val | argOst | argLen | retOst | retLen', output: 'success', description: 'Call external contract' },
	[EvmOpcode.CALLCODE]: { mnemonic: 'CALLCODE', input: 'gas | addr | val | argOst | argLen | retOst | retLen', output: 'success', description: 'Call with caller context' },
	[EvmOpcode.RETURN]: { mnemonic: 'RETURN', input: 'ost | len', output: '', description: 'Return from contract' },
	[EvmOpcode.DELEGATECALL]: { mnemonic: 'DELEGATECALL', input: 'gas | addr | argOst | argLen | retOst | retLen', output: 'success', description: 'Delegate call' },
	[EvmOpcode.CREATE2]: { mnemonic: 'CREATE2', input: 'value | offset | size | salt', output: 'address', description: 'Create at predictable address' },
	[EvmOpcode.STATICCALL]: { mnemonic: 'STATICCALL', input: 'gas | addr | argOst | argLen | retOst | retLen', output: 'success', description: 'Static call (no state change)' },
	[EvmOpcode.REVERT]: { mnemonic: 'REVERT', input: 'ost | len', output: '', description: 'Revert with return data' },
	[EvmOpcode.INVALID]: { mnemonic: 'INVALID', input: '', output: '', description: 'Designated invalid instruction' },
	[EvmOpcode.SELFDESTRUCT]: { mnemonic: 'SELFDESTRUCT', input: 'address', output: '', description: 'Halt and register account for deletion' },
}
