import { EntityType } from '$/data/$EntityType.ts'

export const collectionByEntityType = {
	[EntityType.Actor]: (await import('$/collections/actors.ts')).actorsCollection,
	[EntityType.ActorAllowance]: (await import('$/collections/actor-allowances.ts')).actorAllowancesCollection,
	[EntityType.ActorCoin]: (await import('$/collections/actor-coins.ts')).actorCoinsCollection,
	[EntityType.Block]: (await import('$/collections/blocks.ts')).blocksCollection,
	[EntityType.BridgeRoute]: (await import('$/collections/bridge-routes.ts')).bridgeRouteItemsCollection,
	[EntityType.CctpAllowance]: (await import('$/collections/cctp-allowance.ts')).cctpAllowanceCollection,
	[EntityType.CctpFee]: (await import('$/collections/cctp-fees.ts')).cctpFeesCollection,
	[EntityType.Coin]: (await import('$/collections/coins.ts')).coinsCollection,
	[EntityType.DashboardPanel]: (await import('$/collections/dashboard-panels.ts')).dashboardPanelsCollection,
	[EntityType.Network]: (await import('$/collections/networks.ts')).networksCollection,
	[EntityType.Room]: (await import('$/collections/rooms.ts')).roomsCollection,
	[EntityType.RoomPeer]: (await import('$/collections/room-peers.ts')).roomPeersCollection,
	[EntityType.SharedAddress]: (await import('$/collections/shared-addresses.ts')).sharedAddressesCollection,
	[EntityType.SiweChallenge]: (await import('$/collections/siwe-challenges.ts')).siweChallengesCollection,
	[EntityType.StorkPrice]: (await import('$/collections/stork-prices.ts')).storkPricesCollection,
	[EntityType.SwapQuote]: (await import('$/collections/swap-quotes.ts')).swapQuotesCollection,
	[EntityType.TokenListCoin]: (await import('$/collections/token-list-coins.ts')).tokenListCoinsCollection,
	[EntityType.Transaction]: (await import('$/collections/transactions.ts')).transactionsCollection,
	[EntityType.TransactionSession]: (await import('$/collections/transaction-sessions.ts')).transactionSessionsCollection,
	[EntityType.TransactionSessionSimulation]: (await import('$/collections/transaction-session-simulations.ts')).transactionSessionSimulationsCollection,
	[EntityType.TransferGraph]: (await import('$/collections/transfer-graphs.ts')).transferGraphsCollection,
	[EntityType.TransferRequest]: (await import('$/collections/transfer-requests.ts')).transferRequestsCollection,
	[EntityType.UniswapPool]: (await import('$/collections/uniswap-pools.ts')).uniswapPoolsCollection,
	[EntityType.UniswapPosition]: (await import('$/collections/uniswap-positions.ts')).uniswapPositionsCollection,
	[EntityType.Wallet]: (await import('$/collections/wallets.ts')).walletsCollection,
	[EntityType.WalletConnection]: (await import('$/collections/wallet-connections.ts')).walletConnectionsCollection,
	[EntityType.YellowChannel]: (await import('$/collections/yellow-channels.ts')).yellowChannelsCollection,
	[EntityType.YellowChannelState]: (await import('$/collections/yellow-channel-states.ts')).yellowChannelStatesCollection,
	[EntityType.YellowDeposit]: (await import('$/collections/yellow-deposits.ts')).yellowDepositsCollection,
	[EntityType.YellowTransfer]: (await import('$/collections/yellow-transfers.ts')).yellowTransfersCollection,
}
