import { EntityType } from '$/data/$EntityType.ts'

export const collectionByEntityType = {
	[EntityType.Actor]: (await import('$/collections/Actors.ts')).actorsCollection,
	[EntityType.ActorAllowance]: (await import('$/collections/ActorAllowances.ts')).actorAllowancesCollection,
	[EntityType.ActorCoin]: (await import('$/collections/ActorCoins.ts')).actorCoinsCollection,
	[EntityType.Block]: (await import('$/collections/Blocks.ts')).blocksCollection,
	[EntityType.BridgeRoute]: (await import('$/collections/BridgeRoutes.ts')).bridgeRouteItemsCollection,
	[EntityType.CctpAllowance]: (await import('$/collections/CctpAllowance.ts')).cctpAllowanceCollection,
	[EntityType.CctpFee]: (await import('$/collections/CctpFees.ts')).cctpFeesCollection,
	[EntityType.Coin]: (await import('$/collections/Coins.ts')).coinsCollection,
	[EntityType.DashboardPanel]: (await import('$/collections/DashboardPanels.ts')).dashboardPanelsCollection,
	[EntityType.Network]: (await import('$/collections/Networks.ts')).networksCollection,
	[EntityType.Room]: (await import('$/collections/Rooms.ts')).roomsCollection,
	[EntityType.RoomPeer]: (await import('$/collections/RoomPeers.ts')).roomPeersCollection,
	[EntityType.SharedAddress]: (await import('$/collections/SharedAddresses.ts')).sharedAddressesCollection,
	[EntityType.SiweChallenge]: (await import('$/collections/SiweChallenges.ts')).siweChallengesCollection,
	[EntityType.StorkPrice]: (await import('$/collections/StorkPrices.ts')).storkPricesCollection,
	[EntityType.SwapQuote]: (await import('$/collections/SwapQuotes.ts')).swapQuotesCollection,
	[EntityType.TokenListCoin]: (await import('$/collections/TokenListCoins.ts')).tokenListCoinsCollection,
	[EntityType.Transaction]: (await import('$/collections/Transactions.ts')).transactionsCollection,
	[EntityType.TransactionSession]: (await import('$/collections/TransactionSessions.ts')).transactionSessionsCollection,
	[EntityType.TransactionSessionSimulation]: (await import('$/collections/TransactionSessionSimulations.ts')).transactionSessionSimulationsCollection,
	[EntityType.TransferGraph]: (await import('$/collections/TransferGraphs.ts')).transferGraphsCollection,
	[EntityType.TransferRequest]: (await import('$/collections/TransferRequests.ts')).transferRequestsCollection,
	[EntityType.UniswapPool]: (await import('$/collections/UniswapPools.ts')).uniswapPoolsCollection,
	[EntityType.UniswapPosition]: (await import('$/collections/UniswapPositions.ts')).uniswapPositionsCollection,
	[EntityType.Wallet]: (await import('$/collections/Wallets.ts')).walletsCollection,
	[EntityType.WalletConnection]: (await import('$/collections/WalletConnections.ts')).walletConnectionsCollection,
	[EntityType.YellowChannel]: (await import('$/collections/YellowChannels.ts')).yellowChannelsCollection,
	[EntityType.YellowChannelState]: (await import('$/collections/YellowChannelStates.ts')).yellowChannelStatesCollection,
	[EntityType.YellowDeposit]: (await import('$/collections/YellowDeposits.ts')).yellowDepositsCollection,
	[EntityType.YellowTransfer]: (await import('$/collections/YellowTransfers.ts')).yellowTransfersCollection,
}
