import { EntityType } from '$/data/$EntityType.ts'

export const collectionByEntityType = {
	[EntityType.Actor]: (await import('$/collections/Actors.ts')).actorsCollection,
	[EntityType.ActorAllowance]: (await import('$/collections/ActorAllowances.ts')).actorAllowancesCollection,
	[EntityType.ActorCoin]: (await import('$/collections/ActorCoins.ts')).actorCoinsCollection,
	[EntityType.Block]: (await import('$/collections/Blocks.ts')).blocksCollection,
	[EntityType.BridgeRoute]: (await import('$/collections/BridgeRoutes.ts')).bridgeRouteItemsCollection,
	[EntityType.CctpAllowance]: (await import('$/collections/CctpAllowance.ts')).cctpAllowanceCollection,
	[EntityType.CctpFee]: (await import('$/collections/CctpFees.ts')).cctpFeesCollection,
	[EntityType.Coin]: (await import('$/collections/Coins.ts')).coinsCollection,
	[EntityType.Dashboard]: (await import('$/collections/Dashboards.ts')).dashboardsCollection,
	[EntityType.Eip8004Service]: (await import('$/collections/Eip8004Services.ts')).eip8004ServicesCollection,
	[EntityType.SocialPostSession]: (await import('$/collections/SocialPostSessions.ts')).socialPostSessionsCollection,
	[EntityType.Network]: (await import('$/collections/Networks.ts')).networksCollection,
	[EntityType.Room]: (await import('$/collections/PartykitRooms.ts')).partykitRoomsCollection,
	[EntityType.RoomPeer]: (await import('$/collections/PartykitRoomPeers.ts')).partykitRoomPeersCollection,
	[EntityType.SharedAddress]: (await import('$/collections/SharedAddresses.ts')).sharedAddressesCollection,
	[EntityType.SiweChallenge]: (await import('$/collections/SiweChallenges.ts')).siweChallengesCollection,
	[EntityType.StorkPrice]: (await import('$/collections/StorkPrices.ts')).storkPricesCollection,
	[EntityType.SwapQuote]: (await import('$/collections/SwapQuotes.ts')).swapQuotesCollection,
	[EntityType.TokenListCoin]: (await import('$/collections/TokenListCoins.ts')).tokenListCoinsCollection,
	[EntityType.Transaction]: (await import('$/collections/BridgeTransactions.ts')).bridgeTransactionsCollection,
	[EntityType.Session]: (await import('$/collections/Sessions.ts')).sessionsCollection,
	[EntityType.SessionSimulation]: (await import('$/collections/SessionSimulations.ts')).sessionSimulationsCollection,
	[EntityType.TransferGraph]: (await import('$/collections/TransferGraphs.ts')).transferGraphsCollection,
	[EntityType.TransferRequest]: (await import('$/collections/TransferRequests.ts')).transferRequestsCollection,
	[EntityType.UniswapPool]: (await import('$/collections/UniswapPools.ts')).uniswapPoolsCollection,
	[EntityType.UniswapPosition]: (await import('$/collections/UniswapPositions.ts')).uniswapPositionsCollection,
	[EntityType.Wallet]: (await import('$/collections/Wallets.ts')).walletsCollection,
	[EntityType.WalletConnection]: (await import('$/collections/WalletConnections.ts')).walletConnectionsCollection,
	[EntityType.StateChannel]: (await import('$/collections/StateChannels.ts')).stateChannelsCollection,
	[EntityType.StateChannelState]: (await import('$/collections/StateChannelStates.ts')).stateChannelStatesCollection,
	[EntityType.StateChannelDeposit]: (await import('$/collections/StateChannelDeposits.ts')).stateChannelDepositsCollection,
	[EntityType.StateChannelTransfer]: (await import('$/collections/StateChannelTransfers.ts')).stateChannelTransfersCollection,
}
